### ISSUE TITLE
Error when getting domain information

### ISSUE THREAD

**Issue by ultrasibz** [YWatchman/Laravel-EPP#6]
Hello, I love your package and wanted to get some clarity. Whenever i try and use  Epp::getDomainInfo('***.com') i get the following error
![image](https://user-images.githubusercontent.com/16135819/87306978-22fbc100-c519-11ea-8738-cd2079289b27.png)

Also, is there a way to modify/edit a domain.
Thanks in advance

**Comment by YWatchman** [comment]
Smartified, please look at README. This package is under heavy development, waiting for new release. Metaregistrar is being dropped by this package.
